### ISSUE TITLE
Ensure configuration files align with current standards in the main PatternFly repos

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-extension-seed#35]
- [x] #44
- [x] Check that installing dependencies does not cause any warnings
- [x] Check that dependencies are properly sorted into deps/devDeps/peerDeps
- [ ] #46
- [x] Check that linting does not cause any errors/warnings to be thrown
- [x] Check that tsconfig default settings make sense
- [x] Check that running a build does not cause any errors/warnings
